# Generated by Django 4.1.7 on 2023-06-14 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_remove_movie_isviewed_movielist_isviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDePeliculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_viewed', models.BooleanField()),
                ('is_erased', models.BooleanField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=2)),
                ('genre_name', models.CharField(max_length=100)),
                ('genre_id', models.IntegerField()),
                ('img_url', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('avatar', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='listadepeliculas',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.peliculas'),
        ),
        migrations.AddField(
            model_name='listadepeliculas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuarios'),
        ),
    ]
