# Generated by Django 4.2 on 2023-06-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_listadepeliculas_peliculas_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepeliculas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to='miapp.usuarios'),
        ),
    ]
