# Generated by Django 4.2 on 2023-06-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_listadepeliculas_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepeliculas',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='listadepeliculas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to='miapp.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
