# Generated by Django 4.2 on 2023-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_listadepeliculas_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepeliculas',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
