# Generated by Django 4.2 on 2023-07-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_alter_usuarios_password_alter_usuarios_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='id',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='movie_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
